# Generated by Django 4.0.3 on 2022-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('class_name', models.CharField(max_length=100)),
                ('attack_damage', models.IntegerField()),
                ('ability_damage', models.IntegerField()),
                ('armor', models.IntegerField()),
            ],
        ),
    ]
